name: Test (Linux)

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
      
      - name: Ubuntu packages
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install -y build-essential gcc g++

      - name: Permissions
        shell: bash
        run: sudo chmod -R 777 .

      - name: Build
        shell: bash
        run: ./test_build.sh
